spring:
  profiles:
    active: dev
  application:
    name: sky-take-out
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port}
      password: ${spring.data.redis.password}
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms


sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ${sky.jwt.admin-secret-key}
    # 设置jwt过期时间
    admin-ttl: ${sky.jwt.admin-ttl}
    # 设置前端传递过来的令牌名称
    admin-token-name: ${sky.jwt.admin-token-name}

aliyun:
  oss:
    endpoint: ${aliyun.oss.endpoint}
    region: ${aliyun.oss.region}
    bucketName: ${aliyun.oss.bucketName}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
