spring:
  application:
    name: sky-take-out
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sky_take_out
    username: root
    password: root
  data:
    redis:
      host: 118.178.136.134
      port: 6379
      password: 123456
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms




sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjkl
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    region: cn-beijing
    bucketName: springboot-lim

mybatis:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
